export const FETCH_BEER_LIST_FAIL = 'FETCH_BEER_LIST_FAIL';
export const FETCH_BEER_LIST_SUCCESS = 'FETCH_BEER_LIST_SUCCESS';
export const FETCH_BEER_FAIL = 'FETCH_BEER_FAIL';
export const FETCH_BEER_SUCCESS = 'FETCH_BEER_SUCCESS';
export const OPEN_PANEL = 'OPEN_PANEL';
export const CLOSE_PANEL = 'CLOSE_PANEL';